name: build_conduit_gcc

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_basic:
    name: Ubuntu Build Conduit GCC
    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++
      FC: gfortran
    steps:
    - name: Install System Deps
      run: |
           sudo apt-get update
           sudo apt-get install binutils \
                                gcc \
                                g++ \
                                gfortran \
                                python3 \
                                python3-dev \
                                python3-venv \
                                perl \
                                git \
                                git-lfs \
                                curl \
                                wget \
                                tar \
                                unzip \
                                build-essential \
                                libncurses-dev \
                                libssl-dev \
                                libblas-dev \
                                liblapack-dev \
                                zlib1g-dev \
                                libgdbm-dev \
                                libreadline-dev \
                                libsqlite3-dev \
                                libbz2-dev \
                                openmpi-bin \
                                openmpi-common \
                                libopenmpi-dev \
                                cmake
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Env Info
      run: |
        echo "**** Env Info"
        cmake --version
        gcc --version
        which mpicc
    - name: Build TPLs
      run: |
        env enable_mpi=ON \
            enable_fortran=ON \
            enable_tests=OFF \
            enable_verbose=OFF \
            build_caliper=true \
            build_conduit=false \
            build_jobs=2 \
            ./scripts/build_conduit/build_conduit.sh
    - name: Configure Conduit
      run: |
        echo "**** Configuring Conduit"
        cmake -S src -B build -C conduit-config.cmake -DCMAKE_INSTALL_PREFIX=install
    - name: Build Conduit
      run: |
        echo "**** Building Conduit"
        cmake --build build -j2
    - name: Install Conduit
      run: |
        echo "**** Installing Conduit"
        cmake --install build
    - name: Check Install
      run: |
        echo "**** Checking Conduit using-with-cmake-mpi example"
        export CC=/usr/bin/mpicc
        export CXX=/usr/bin/mpicxx
        cd install/examples/conduit/using-with-cmake-mpi
        cmake -S . -B build
        cmake --build build --verbose -j2
        mpiexec -n 2 ./build/conduit_mpi_example
  build_basic_pyvenv:
    name: Ubuntu Build Conduit GCC with Python VENV
    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++
      FC: gfortran
    steps:
    - name: Install System Deps
      run: |
           sudo apt-get update
           sudo apt-get install binutils \
                                gcc \
                                g++ \
                                gfortran \
                                python3 \
                                python3-dev \
                                python3-venv \
                                perl \
                                git \
                                git-lfs \
                                curl \
                                wget \
                                tar \
                                unzip \
                                build-essential \
                                libncurses-dev \
                                libssl-dev \
                                libblas-dev \
                                liblapack-dev \
                                zlib1g-dev \
                                libgdbm-dev \
                                libreadline-dev \
                                libsqlite3-dev \
                                libbz2-dev \
                                openmpi-bin \
                                openmpi-common \
                                libopenmpi-dev \
                                cmake
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Env Info
      run: |
        echo "**** Env Info"
        cmake --version
        gcc --version
        which mpicc
    - name: Build TPLs
      run: |
        env enable_mpi=ON \
            enable_fortran=ON \
            enable_tests=OFF \
            enable_verbose=OFF \
            build_conduit=false \
            enable_python=ON \
            build_pyvenv=true \
            build_jobs=2 \
            ./scripts/build_conduit/build_conduit.sh
    - name: Configure Conduit
      run: |
        echo "**** Configuring Conduit"
        cmake -S src -B build -C conduit-config.cmake -DCMAKE_INSTALL_PREFIX=install
    - name: Build Conduit
      run: |
        echo "**** Building Conduit"
        cmake --build build -j2
    - name: Install Conduit
      run: |
        echo "**** Installing Conduit"
        cmake --install build
    - name: Check Install
      run: |
        echo "**** Checking Conduit using-with-cmake-mpi example"
        export CC=/usr/bin/mpicc
        export CXX=/usr/bin/mpicxx
        cd install/examples/conduit/using-with-cmake-mpi
        cmake -S . -B build
        cmake --build build --verbose -j2
        mpiexec -n 2 ./build/conduit_mpi_example
